version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /kafka-logs
      KAFKA_CLUSTER_ID: my-cluster-id-12345
    volumes:
      - kafka_data:/kafka-logs
    command:
      - sh
      - -c
      - |
        if [ ! -f /kafka-logs/meta.properties ]; then
          /opt/kafka/bin/kafka-storage.sh format -t my-cluster-id-12345 -c /opt/kafka/config/kraft/server.properties
        fi && /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vivek
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  kafka_data:
  pgdata:
